
PageLogger:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL, or NONE.
  path: ./pagelogs/aime/gpt4o_self_teaching_3

client:
  model: gpt-4o-2024-08-06  # gpt-4o-2024-05-13, gpt-4o-2024-08-06, gpt-4o-2024-11-20, o1-preview, o1, etc.
  provider: trapi  # openai, azure_openai, or trapi
  # api_key: sk-  # only for openai
  temperature: 0.8
  max_completion_tokens: 4096
  presence_penalty: 0.0
  frequency_penalty: 0.0
  top_p: 1.0
  max_retries: 65535

Apprentice:
  name_of_agent_or_team: AssistantAgent  # AssistantAgent or MagenticOneGroupChat
  disable_prefix_caching: 1  # If true, prepends a small random string to the context, to decorrelate repeated runs.
  MemoryController:
    max_train_trials: 10  # 2-10
    max_test_trials: 3  # 1-3
    MemoryBank:
      path: ./memory_bank/gpt4o_self_teaching
      relevance_conversion_threshold: 1.7
      n_results: 25
      distance_threshold: 100

evaluations:
  - eval_function:
      function_name: eval_self_teaching
      module_path: ./eval_functions/eval_self_teaching.py
      num_loops: 10  # 1-10
      num_final_test_trials: 3  # 1-3
    runs:
      - task_file_1: data_files/tasks/aime/3/31.yaml   # 78
        task_file_2: data_files/tasks/aime/3/31.yaml   # 78

      - task_file_1: data_files/tasks/aime/3/87.yaml   # 58
        task_file_2: data_files/tasks/aime/3/87.yaml   # 58

      - task_file_1: data_files/tasks/aime/3/103.yaml  # 78
        task_file_2: data_files/tasks/aime/3/103.yaml  # 78

      - task_file_1: data_files/tasks/aime/3/117.yaml  # 60
        task_file_2: data_files/tasks/aime/3/117.yaml  # 60

      - task_file_1: data_files/tasks/aime/3/153.yaml  # 82
        task_file_2: data_files/tasks/aime/3/153.yaml  # 82

      - task_file_1: data_files/tasks/aime/3/169.yaml  # 66
        task_file_2: data_files/tasks/aime/3/169.yaml  # 66

      - task_file_1: data_files/tasks/aime/3/269.yaml  # 84
        task_file_2: data_files/tasks/aime/3/269.yaml  # 84

      - task_file_1: data_files/tasks/aime/3/303.yaml  # 50
        task_file_2: data_files/tasks/aime/3/303.yaml  # 50

      - task_file_1: data_files/tasks/aime/3/309.yaml  # 56  ?
        task_file_2: data_files/tasks/aime/3/309.yaml  # 56

      - task_file_1: data_files/tasks/aime/3/352.yaml  # 56
        task_file_2: data_files/tasks/aime/3/352.yaml  # 56

      - task_file_1: data_files/tasks/aime/3/366.yaml  # 72
        task_file_2: data_files/tasks/aime/3/366.yaml  # 72

      - task_file_1: data_files/tasks/aime/3/381.yaml  # 72
        task_file_2: data_files/tasks/aime/3/381.yaml  # 72

      - task_file_1: data_files/tasks/aime/3/399.yaml  # 66
        task_file_2: data_files/tasks/aime/3/399.yaml  # 66

      - task_file_1: data_files/tasks/aime/3/495.yaml  # 94
        task_file_2: data_files/tasks/aime/3/495.yaml  # 94

      - task_file_1: data_files/tasks/aime/3/510.yaml  # 84
        task_file_2: data_files/tasks/aime/3/510.yaml  # 84

      - task_file_1: data_files/tasks/aime/3/524.yaml  # 60
        task_file_2: data_files/tasks/aime/3/524.yaml  # 60

      - task_file_1: data_files/tasks/aime/3/595.yaml  # 60
        task_file_2: data_files/tasks/aime/3/595.yaml  # 60

      - task_file_1: data_files/tasks/aime/3/627.yaml  # 62
        task_file_2: data_files/tasks/aime/3/627.yaml  # 62

      - task_file_1: data_files/tasks/aime/3/635.yaml  # 52
        task_file_2: data_files/tasks/aime/3/635.yaml  # 52

      - task_file_1: data_files/tasks/aime/3/653.yaml  # 70
        task_file_2: data_files/tasks/aime/3/653.yaml  # 70
