
PageLogger:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL, or NONE.
  path: ~/pagelogs/temp25

client:
  model: gpt-4o-2024-08-06  # gpt-4o-2024-05-13, gpt-4o-2024-08-06, o1-preview, o1, etc.
  provider: trapi  # openai, azure_openai, or trapi
  # api_key: sk-  # only for openai
  temperature: 0.8
  max_completion_tokens: 4096
  presence_penalty: 0.0
  frequency_penalty: 0.0
  top_p: 1.0
  max_retries: 65535
  ClientWrapper:  # Provides record & replay functionality
    enabled: 1  # Only works for AssistantAgent currently
    mode: check-replay  # pass-through, record, or check-replay
    session_name: short-3b

Apprentice:
  name_of_agent_or_team: AssistantAgent  # AssistantAgent or MagenticOneGroupChat
  disable_prefix_caching: 0  # If true, prepends a small random string to the context, to decorrelate repeated runs.
  TaskCentricMemoryController:
    max_train_trials: 2  # 2-10
    max_test_trials: 1  # 1-3
    TaskCentricMemoryBank:
      path: ~/task_centric_memory_bank/temp
      relevance_conversion_threshold: 1.7
      n_results: 25
      distance_threshold: 100

evaluations:
  - eval_function:
      function_name: eval_teachability
      module_path: ame.eval_functions.eval_teachability
    runs:
      - task_file: data_files/tasks/autogen_package.yaml  # The task being tested.
        insight_file: data_files/insights/add_topic.yaml  # Advice provided to help solve the task.

  - eval_function:
      function_name: eval_learning_from_demonstration
      module_path: ame.eval_functions.eval_learning_from_demonstration
      num_trials: 1  # 1-10
    runs:
      - main_task_file: data_files/tasks/cell_towers_1.yaml  # The task being tested.
        demo_task_file: data_files/tasks/cell_towers_2.yaml  # A similar but different task.
        demo_solution_file: data_files/insights/cell_towers_2_demo.yaml  # A demonstration of solving the second.

  - eval_function:
      function_name: eval_self_teaching
      module_path: ame.eval_functions.eval_self_teaching
      num_loops: 1  # 1-10
      num_final_test_trials: 1  # 1-3
    runs:
      - task_file_1: data_files/tasks/10_liars.yaml  # Train and test on this task.
        task_file_2: data_files/tasks/100_vampires.yaml  # Test generalization on this different, similar task.
